version: '3'
services:
  microservice-flask:
      build:
        context: ./microservice
      volumes:
      - "./microservice:/micro_service/"
      image: microservice-flask
      restart: unless-stopped
      ports:
      - "404:5000"
      command: python app.py

  apache:
    image: httpd:latest
    container_name: frontend
    ports:
    - '666:80'
    volumes:
    - './frontend/dist:/usr/local/apache2/htdocs'
