version: '3'
services:
  microservice-flask:
      build: 
        context: ./microservice
      volumes:
        - "./microservice/:/micro_service/"
      image: microservice-flask                  
      restart: unless-stopped
      ports:
            - "404:5000"
      command: python app.py



